apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lz-http-zone-forward
  namespace: edge-routing
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`^([a-z0-9-]+\.)*levizitting\.com$`) && !Host(`headscale.levizitting.com`) && !Host(`levizitting.com`)
      services:
        - name: lz-k3s-01
          port: 80
          weight: 1
        - name: lz-k3s-02
          port: 80
          weight: 1
