apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/traefik
  - infrastructure/coredns
  - infrastructure/external-secrets
  - infrastructure/cert-manager
  - infrastructure/reloader
  - apps
