apiVersion: v1
kind: Service
metadata:
  name: edge-dns
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: edge-dns
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
