apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headplane-config
  namespace: headscale
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: k8s-headscale
    kind: SecretStore
  target:
    name: headplane-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: headplane-config-template
            items:
              - key: config.yaml
                templateAs: Values
  dataFrom:
    - extract:
        key: headplane-runtime
