apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/glitchedmob/infra-public-edge.git
  ref:
    branch: main
  secretRef:
    name: flux-git-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: public-vps
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
