apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-sgfdevs-k3s.yaml
  - ingressroute-http-zone-forward.yaml
  - ingressroutetcp-sgfdev-zone-passthrough.yaml
