apiVersion: v1
kind: Service
metadata:
  name: sgfdevs-k3s-01
  namespace: edge-routing
spec:
  type: ExternalName
  externalName: sgfdevs-k3s-01.headnet.levizitting.com
  ports:
    - name: http
      port: 80
      targetPort: 80
