apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2.3.2-slim
          volumeMounts:
            - name: data
              mountPath: /app/data
          ports:
            - containerPort: 3001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data