apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-kuma-k8up-repo-password
  namespace: uptime-kuma
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: uptime-kuma-k8s
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: uptime-kuma-secrets
        property: uptimeKumaResticPassword