apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8up-b2-credentials
  namespace: uptime-kuma
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: uptime-kuma-k8s
    kind: ClusterSecretStore
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: uptime-kuma-secrets
        property: b2AccountId
    - secretKey: account-key
      remoteRef:
        key: uptime-kuma-secrets
        property: b2AccountKey