apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: uptime-kuma-backup
  namespace: uptime-kuma
  labels:
    backup.k8up.io/app: uptime-kuma
spec:
  backupCommand: >-
    sh -c '
      mkdir -p /tmp/backup &&
      sqlite3 /app/data/kuma.db ".backup /tmp/backup/kuma.db" &&
      tar -cf - -C /tmp/backup .
    '
  fileExtension: .tar
  pod:
    spec:
      containers:
        - name: backup
          image: keinos/sqlite3:3.53.2
          command:
            - sh
            - -c
            - sleep 3600
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
      securityContext:
        runAsUser: 0
