apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - helmrepository.yaml
  - externalsecret-dex-hash.yaml
  - externalsecret-dex-client.yaml
  - helmrelease.yaml
