- op: replace
  path: /metadata/name
  value: headscale-backup
- op: replace
  path: /metadata/labels/backup.k8up.io~1app
  value: headscale
- op: replace
  path: /spec/backupCommand
  value: >-
    sh -c '
      mkdir -p /tmp/backup &&
      sqlite3 /data/db.sqlite ".backup /tmp/backup/db.sqlite" &&
      [ -f /data/private.key ] && cp /data/private.key /tmp/backup/ || true &&
      cp /data/noise_private.key /tmp/backup/ &&
      cp /data/derp_server_private.key /tmp/backup/ &&
      tar -cf - -C /tmp/backup .
    '
- op: replace
  path: /spec/pod/spec/volumes/0/persistentVolumeClaim/claimName
  value: headscale-data
