apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headscale-k8up-repo-password
  namespace: headscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: headscale-k8s
    kind: ClusterSecretStore
  target:
    name: headscale-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: headscale-secrets
        property: headscaleResticPassword
