apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8up-b2-credentials
  namespace: headscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: /homelab/public-edge/backups/b2-account-id
    - secretKey: account-key
      remoteRef:
        key: /homelab/public-edge/backups/b2-account-key
