apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headscale-k8up-repo-password
  namespace: headscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: headscale-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /homelab/public-edge/backups/headscale/restic-password
