apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: headscale-config-template
    files:
      - config.yaml=config.yaml.tmpl
resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - k8up-schedule.yaml
  - externalsecret-config.yaml
  - externalsecret-k8up-b2-credentials.yaml
  - externalsecret-k8up-repo-password.yaml
  - eso-k8s-store.yaml
