apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale
  annotations:
    k8up.io/backup: "false"
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-retain
