apiVersion: v1
kind: Service
metadata:
  name: headscale
  namespace: headscale
spec:
  type: LoadBalancer
  selector:
    app: headscale
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: stun
