apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor-next-impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capacitor-next-impersonator
subjects:
  - kind: ServiceAccount
    name: capacitor-next
    namespace: capacitor
