apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capacitor-secrets
  namespace: capacitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: capacitor-secrets
    creationPolicy: Owner
  data:
    - secretKey: USERS
      remoteRef:
        key: /homelab/x86-vps-node-01/capacitor-admin-password-bcrypt
