apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headplane-secrets
  namespace: headscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: headscale-k8s
    kind: ClusterSecretStore
  target:
    name: headplane-secrets
    creationPolicy: Owner
  data:
    - secretKey: cookie_secret
      remoteRef:
        key: headscale-secrets
        property: cookieSecret
