apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: headplane-config-template
    files:
      - config.yaml=config.yaml.tmpl
resources:
  - ../backup-base
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - externalsecret.yaml
  - externalsecret-config.yaml
  - externalsecret-k8up-repo-password.yaml
patches:
  - path: backup-patch.yaml
    target:
      kind: PreBackupPod
      name: app-backup
  - path: schedule-patch.yaml
    target:
      kind: Schedule
      name: app-backup
