apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  namespace: headscale
  annotations:
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: "local-path"
