apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  namespace: headscale
  labels:
    backup.k8up.io/app: headplane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: "local-path"
