- op: replace
  path: /metadata/name
  value: headplane-backup
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: headplane-k8up-repo-password
- op: replace
  path: /spec/backend/b2/path
  value: headplane
- op: replace
  path: /spec/backup/schedule
  value: '20 8 * * *'
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: headplane
- op: replace
  path: /spec/check/schedule
  value: '20 9 * * 1'
- op: replace
  path: /spec/prune/schedule
  value: '20 10 * * 0'
