apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-oidc-edge
  namespace: k8s-oidc
spec:
  secretName: k8s-oidc-edge-tls
  dnsNames:
    - k8s-oidc-edge.levizitting.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
