name: Ansible Auto

on:
  push:
    branches: [main]
    paths:
      - ansible/playbooks/apply.yml
      - ansible/playbooks/manifests/**

permissions:
  contents: read
  id-token: write

jobs:
  run:
    uses: glitchedmob/infra-gha/.github/workflows/ansible-auto.yml@v0.5.1
    with:
      working-directory: ansible
      trigger-map: '{"apply.yml": ["playbooks/apply.yml", "playbooks/manifests"]}'
    secrets:
      output_encryption_key: ${{ secrets.OUTPUT_ENCRYPTION_KEY }}
