name: Ansible Run

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: Playbook to run
        required: true
        type: choice
        options:
          - bootstrap.yml
          - apply.yml

permissions:
  contents: read
  id-token: write

jobs:
  run:
    uses: glitchedmob/infra-gha/.github/workflows/ansible-run.yml@v0.6.0
    with:
      working-directory: ansible
      playbook: ${{ inputs.playbook }}
    secrets:
      output_encryption_key: ${{ secrets.OUTPUT_ENCRYPTION_KEY }}
