name: Ansible Run

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: Playbook to run
        required: true
        type: choice
        options:
          - bootstrap.yml
          - apply.yml

permissions:
  contents: read
  id-token: write

jobs:
  run:
    uses: glitchedmob/infra-gha/.github/workflows/ansible-run.yml@v0.7.0
    with:
      working-directory: src/ansible
      initialize-terraform: true
      terraform-working-directory: src/tf
      playbook: ${{ inputs.playbook }}
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      output_encryption_key: ${{ secrets.OUTPUT_ENCRYPTION_KEY }}
