name: Ansible Auto

on:
  push:
    branches: [main]
    paths:
      - src/ansible/playbooks/apply.yml
      - src/ansible/playbooks/manifests/**
      - .github/workflows/ansible-auto.yml

permissions:
  contents: read
  id-token: write

jobs:
  run:
    uses: glitchedmob/infra-gha/.github/workflows/ansible-auto.yml@v0.7.0
    with:
      working-directory: src/ansible
      initialize-terraform: true
      terraform-working-directory: src/tf
      trigger-map: '{"apply.yml": ["src/ansible/playbooks/apply.yml", "src/ansible/playbooks/manifests"]}'
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      output_encryption_key: ${{ secrets.OUTPUT_ENCRYPTION_KEY }}
